language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm test"
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        on:
          tags: true
          branch: master
